% PHASE_OF_FLIGHT.m
% Given a table of the phases of flight, previously generated by our 
% acceleration data processing functions, determines the phase of flight 
% at the time t. The variable t is a scalar or vector.

% Acceleration data starts at a different time from the sequencing data, so
% need to take into account the offset in their start times. When passing
% in sequencing time, first correct it for the offset...
% t = t_sequencing_start - t_acceleration_start + t_base

function phase = phase_of_flight(table,t)
    if numel(t)==1,
        phase = phase_of_flight_helper(t);
    else
        phase = arrayfun(@phase_of_flight_helper,t);
    end
    
    function phase_of_flight_helper(t0)
        % Look of phase of flight for time t0 using table
        
    end
end
